import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { CashFlowPoint, CategoryPoint, ComparisonPoint, DashboardFilters } from "../../api/dashboard";

export const control = "h-10 min-w-0 rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring";
const palette = ["var(--primary)", "#38bdf8", "#a78bfa", "#fb7185", "#fbbf24", "#94a3b8"];
type Ref = { id: number; name: string; is_active: boolean };
type ChartProps = { formatMinor: (value: number) => string };

export function Card({ title, context, children, className = "" }: { title: string; context: string; children: React.ReactNode; className?: string }) { return <section className={`min-w-0 rounded-xl border bg-card p-5 shadow-sm ${className}`}><div className="mb-5"><h2 className="font-semibold tracking-tight">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{context}</p></div>{children}</section>; }

export function DashboardFiltersControl({ filters, onChange, accounts = [], categories = [], tags = [], label = "Dashboard filters" }: { filters: DashboardFilters; onChange: (filters: DashboardFilters) => void; accounts?: Ref[]; categories?: Ref[]; tags?: Ref[]; label?: string }) {
  const update = (key: keyof DashboardFilters, value: string) => onChange({ ...filters, [key]: value ? (key.endsWith("_id") ? Number(value) : value) : undefined } as DashboardFilters);
  return <section className="rounded-xl border bg-card p-4 shadow-sm" aria-label={label}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
    <label className="grid gap-1 text-xs font-medium text-muted-foreground">From<input className={control} type="date" value={filters.start_date} onChange={(event) => update("start_date", event.target.value)} /></label><label className="grid gap-1 text-xs font-medium text-muted-foreground">To<input className={control} type="date" value={filters.end_date} onChange={(event) => update("end_date", event.target.value)} /></label>
    <label className="grid gap-1 text-xs font-medium text-muted-foreground">Account<select className={control} value={filters.financial_account_id ?? ""} onChange={(event) => update("financial_account_id", event.target.value)}><option value="">All accounts</option>{accounts.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <label className="grid gap-1 text-xs font-medium text-muted-foreground">Category<select className={control} value={filters.category_id ?? ""} onChange={(event) => update("category_id", event.target.value)}><option value="">All categories</option>{categories.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <label className="grid gap-1 text-xs font-medium text-muted-foreground">Tag<select className={control} value={filters.tag_id ?? ""} onChange={(event) => update("tag_id", event.target.value)}><option value="">All tags</option>{tags.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
  </div></section>;
}

export function CashFlowCard({ data, context, formatMinor, shortDate }: ChartProps & { data: CashFlowPoint[]; context: string; shortDate: (value: string) => string }) { return <Card title="Cash flow" context={context}><div className="h-72">{data.every((item) => !item.income_minor && !item.expense_minor) ? <p className="grid h-full place-items-center text-sm text-muted-foreground">No cash flow in this period.</p> : <ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid vertical={false} strokeDasharray="3 3" /><XAxis dataKey="date" tickFormatter={shortDate} /><YAxis tickFormatter={(value) => formatMinor(value)} width={72} /><Tooltip formatter={(value) => formatMinor(Number(value))} labelFormatter={(value) => shortDate(String(value))} /><Legend /><Bar dataKey="income_minor" name="Income" fill="#22c55e" radius={[4, 4, 0, 0]} /><Bar dataKey="expense_minor" name="Expenses" fill="#f97316" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer>}</div></Card>; }
export function PeriodComparisonCard({ data, context, emptyLabel, formatMinor, shortDate }: ChartProps & { data: ComparisonPoint[]; context: string; emptyLabel: string; shortDate: (value: string) => string }) { return <Card title="Period comparison" context={context}><div className="h-72">{data.every((item) => !item.current_minor && !item.previous_minor && !item.prior_year_minor) ? <p className="grid h-full place-items-center text-sm text-muted-foreground">{emptyLabel}</p> : <ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid vertical={false} strokeDasharray="3 3" /><XAxis dataKey="label" tickFormatter={shortDate} /><YAxis tickFormatter={(value) => formatMinor(value)} width={72} /><Tooltip formatter={(value) => formatMinor(Number(value))} /><Legend /><Line dataKey="current_minor" name="Current" stroke="var(--primary)" strokeWidth={2} dot={false} /><Line dataKey="previous_minor" name="Previous" stroke="#38bdf8" dot={false} /><Line dataKey="prior_year_minor" name="Prior year" stroke="#a78bfa" dot={false} /></LineChart></ResponsiveContainer>}</div></Card>; }
export function CategorySpendingCard({ data, context, formatMinor }: ChartProps & { data: CategoryPoint[]; context: string }) { return <Card title="Category spending" context={context}><div className="h-72">{data.length === 0 ? <p className="grid h-full place-items-center text-sm text-muted-foreground">No category spending in this period.</p> : <ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{ left: 20 }}><CartesianGrid horizontal={false} strokeDasharray="3 3" /><XAxis type="number" tickFormatter={(value) => formatMinor(value)} /><YAxis dataKey="name" type="category" width={90} /><Tooltip formatter={(value) => formatMinor(Number(value))} /><Bar dataKey="amount_minor" name="Expenses" fill="var(--primary)" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer>}</div></Card>; }
export function ExpenseStructureCard({ data, formatMinor }: ChartProps & { data: CategoryPoint[] }) { return <Card title="Expense structure" context="Top five categories and Other"><div className="h-72">{data.length === 0 ? <p className="grid h-full place-items-center text-sm text-muted-foreground">No expenses to structure.</p> : <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="amount_minor" nameKey="name" innerRadius={58} outerRadius={92} paddingAngle={2}>{data.map((item, index) => <Cell key={item.name} fill={palette[index % palette.length]} />)}</Pie><Tooltip formatter={(value) => formatMinor(Number(value))} /><Legend /></PieChart></ResponsiveContainer>}</div></Card>; }
